apiVersion: v2
name: sbomer-platform-chart
description: Umbrella chart for SBOMer components and Dev infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: manifest-storage-service-chart
    version: 0.1.15
    repository: "oci://quay.io/sbomer"
  - name: sbom-service-chart
    version: 0.1.21
    repository: "oci://quay.io/sbomer"
  - name: syft-generator-chart
    version: 0.1.12
    repository: "oci://quay.io/sbomer"
  - name: ui-chart
    version: 0.1.20
    repository: "oci://quay.io/sbomer"
  - name: dependency-track
    version: 0.41.0
    repository: "https://dependencytrack.github.io/helm-charts"
    condition: global.includeDependencyTrack
