{{- if .Values.global.includeStatusDb }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-status-db
  labels:
    app: status-db
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: status-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-db
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.infra.statusDb.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            # --- STANDARD STATUS-DB VARS ---
            - name: POSTGRESQL_DATABASE
              valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-status-db-secret, key: postgres-db-name } }
            - name: POSTGRESQL_USER
              valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-status-db-secret, key: postgres-username } }
            - name: POSTGRESQL_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-status-db-secret, key: postgres-password } }

            # --- EXTENSION: UNLEASH VARS ---
            # We inject these only if Unleash is enabled
            {{- if .Values.global.includeUnleash }}
            - name: UNLEASH_DB_NAME
              valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-unleash-secret, key: postgres-db-name } }
            - name: UNLEASH_DB_USER
              valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-unleash-secret, key: postgres-username } }
            - name: UNLEASH_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-unleash-secret, key: postgres-password } }
            {{- end }}

          volumeMounts:
            - name: additional-dbs
              # CHANGE THIS LINE:
              mountPath: /opt/app-root/src/postgresql-init/01-create-additional-dbs.sh
              subPath: 01-create-additional-dbs.sh

      volumes:
        - name: db-data
          emptyDir: {}
        # --- CONFIGMAP VOLUME ---
        - name: additional-dbs
          configMap:
            name: {{ .Release.Name }}-additional-dbs-init-script
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-status-db
  labels:
    app.kubernetes.io/name: status-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.infra.statusDb.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: status-db
{{- end }}